language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
       
before_install:
    - eval "${MATRIX_EVAL}"

# Build and steps
script:
  - mkdir build
  - cd build
  - wget https://cmake.org/files/v3.10/cmake-3.10.3.tar.gz
  - tar -xzf cmake-3.10.3.tar.gz
  - cd cmake-3.10.3
  - ./configure
  - make
  - cd ..
  - ./cmake-3.10.3/bin/cmake ..
  - make
  - ./../util/test_script.sh  
